name: app_zoologico
description: A new Flutter project.

publish_to: 'none' # Si no planeas publicar tu proyecto en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Esto habilita las características de super-parameters

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  # Para íconos en estilo iOS
  flutter_svg: ^2.0.10+1
  carousel_slider: ^5.0.0
  firebase_core: ^3.7.0
  firebase_auth: ^5.3.2
  provider: ^5.0.0
  http: ^1.2.2
  flip_card: ^0.7.0
  sqflite: ^2.2.0
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0  # Reglas de linting recomendadas para buenos hábitos de codificación

flutter:
  uses-material-design: true

  assets:
    - assets/galeria/  # Ruta a tu carpeta de imágenes
    - assets/images/  # Ruta a tu carpeta de imágenes

