name: app_zoologico
description: A new Flutter project.

publish_to: 'none' # Si no planeas publicar tu proyecto en pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"  # Esto habilita las características de super-parameters

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2  # Para íconos en estilo iOS

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0  # Reglas de linting recomendadas para buenos hábitos de codificación

flutter:
  uses-material-design: true

  assets:
    - assets/galeria/  # Ruta a tu carpeta de imágenes
